### ISSUE TITLE
Desenvolver a página institucional

### ISSUE THREAD

**Issue by fabricioifc** [fabricioifc/rota-da-amizade-app#17]
Precisamos desenvolver uma página institucional para a rota da amizade. A página estava publicada no endereço https://rotadaamizade.com.br. 

A página precisa ter:

**- Uma página inicial** com uma imagem de fundo e esse texto (A Rota da Amizade Convention & Visitors Bureau é uma associação de turismo sem fins econômicos que atualmente integra os municípios de Arroio Trinta, Fraiburgo, Iomerê, Pinheiro Preto, Tangará, Treze Tílias e Videira e possui associados nos Municípios de Campos Novos, Piratuba e Herval D'Oeste. Através da divulgação dos municípios e de seus associados, busca promover e desenvolver o turismo na região do Vale dos Imigrantes.)

**- Uma página com a história da rota**
 **- Uma página com os associados** com o logotipo de cada associado separado por categoria (diamante, ouro, prata)
 **- Uma página de contato** com redes sociais e link para o aplicativo
** - Um rodapé padrão em todas as telas**
 - Uma barra de navegação.

Pode optar por fazer uma única página em que as informações aparecem ao rola o mouse.

Recomendo usar a biblioteca Vite com React e uma biblioteca CSS para os estilos e pequenas animações.

No mesmo repositório do GitHub, crie uma pasta separada para esse projeto.

**Comment by fabricioifc** [comment]
Se tiver dúvidas me avise

**Comment by matheuswogt37** [comment]
30/08/23
Continuei a trabalhar na responsividade do header, falta ajeitar o menu de opções mobile para ocupar todo o espaço
Foi colocado mais texto na sessão "quem somos" e trocado a imagem de fundo de fraiburgo, não é associada, para videira, associada.
Começado a sessão de municípios e decidido ser implementado em cards, ainda a decidir entre 4 e 5 cards no desktop, e entre 1 e 2 no mobile, e falta terminar o design dos cards em sí

**Comment by matheuswogt37** [comment]
01/09/23
Esta sendo retrabalhado o header para que se adapte mais facilmente ao mobile, utilizando agora useEffect
Commitado em um branch 7-site-institucional o estudo do início do período

**Comment by matheuswogt37** [comment]
04/09
Provisoriamente o header foi desenvolvido de forma responsiva

**Comment by matheuswogt37** [comment]
05/09
começado a seção dos municipios por meio de carda, falta aplicar a responsividade e decidir mais sobre a animação do box-shadow

**Comment by matheuswogt37** [comment]
18/09
feito a troca de páginas só recarregar o componente principal, funcional tanto para desktop e mobile, pequenas alterações no footer

**Comment by matheuswogt37** [comment]
20/19
continuado o desenvolvimento da pagina quem somos, dividido os cards de municipios e associados em suas respectivas paginas

**Comment by matheuswogt37** [comment]
26/09
código da descrição pag inicial alterado, terminada sessão faça parte, definido uma pagina para contato ainda não finalizada

**Comment by fabricioifc** [comment]
Transferida para outro repositório
